version: "3.9"
services:
  app:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=ecto://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_VALID_FOR_HOURS=${JWT_VALID_FOR_HOURS}
    depends_on:
      database:
        condition: service_healthy
    stdin_open: true
    tty: true
  database:
    image: "postgres:14.2-alpine"
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
