name: "Build and test"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 24
          elixir-version: 1.14
      - run: mix deps.get
      - run: mix credo --strict
      - run: mix format --check-formatted
      - run: mix test
